# Generated by Django 3.2.7 on 2021-10-04 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('name_company', models.CharField(default='', max_length=100)),
                ('date_created', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(default='', max_length=100)),
                ('company_pic', models.CharField(default='noimage.png', max_length=100)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_pic', models.CharField(default='noimage.png', max_length=100)),
                ('driver_fullname', models.CharField(default='', max_length=100)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezbook_admin.company')),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='Travel_Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'travel_places',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pic', models.CharField(default='noimage.png', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('firstname', models.CharField(default='', max_length=100)),
                ('middlename', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_created', models.DateField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate', models.CharField(default='', max_length=100)),
                ('vehicle_capacity', models.IntegerField()),
                ('vehicle_type', models.CharField(default='', max_length=100)),
                ('vehicle_pic', models.CharField(default='noimage.png', max_length=100)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezbook_admin.company')),
                ('vehicle_driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezbook_admin.driver')),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='BookTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_travel_date', models.DateField()),
                ('available_travel_time', models.TimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezbook_admin.company')),
                ('place_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_from', to='ezbook_admin.travel_places')),
                ('place_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_to', to='ezbook_admin.travel_places')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezbook_admin.vehicle')),
            ],
            options={
                'db_table': 'booktravel',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('seat_number', models.IntegerField()),
                ('book_travel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezbook_admin.booktravel')),
                ('user_travel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezbook_admin.user')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
